services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DEV: true
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - neo4j
    volumes:
      - ./backend:/app

  frontend:
    container_name: frontend
    build:
      context: ./front_financa
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front_financa:/app
      - /app/node_modules
    env_file:
      - ./front_financa/.env

  neo4j:
    container_name: neo4j
    image: neo4j:5.13
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_memory_heap_initial__size=512M
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
