version: "3.8"
services:
  financa-db:
    container_name: financa-db
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest-network
  backend-financa:
    container_name: backend-financa
    restart: unless-stopped
    build:
      context: ./backend_financa
      dockerfile: Dockerfile
    env_file:
      - ./backend_financa/.env
    ports:
      - 3001:3001
    networks:
      - finance-net
      - nest-network
    command: yarn start:debug

  front-cad-financa:
    container_name: front-cad-financa
    restart: unless-stopped
    build:
      context: ./front_cad_financa
      dockerfile: Dockerfile
    env_file:
      - ./front_cad_financa/.env
    ports:
      - 5173:5173
    networks:
      - finance-net
    command: yarn dev

networks:
  finance-net:
    driver: bridge
  nest-network:
    driver: bridge

volumes:
  postgres_data: