FROM python:3.10-slim

# Instalar dependências do sistema
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Instalar pipenv
RUN pip install --no-cache-dir pipenv

# Copiar arquivos de dependência
COPY Pipfile Pipfile.lock ./

# Instalar dependências do projeto
ENV PIPENV_VENV_IN_PROJECT=1
RUN pipenv install --deploy --system

# Copiar o resto do código
COPY /app ./

EXPOSE 3001

CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "3001", "--reload"]