"""corrigir drop tabela usuários inserir foreign_key users em transactions

Revision ID: 0d838f473b20
Revises: 3b998bc9e703
Create Date: 2025-08-21 14:36:37.231301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d838f473b20'
down_revision: Union[str, Sequence[str], None] = '3b998bc9e703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
