"""Add empresas and usuarios tables

Revision ID: 4355b5d6f028
Revises: 
Create Date: 2025-08-20 15:25:24.388845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4355b5d6f028'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'empresas', ['empresa_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'usuarios', ['usuario_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'empresa_id')
    op.drop_column('transactions', 'usuario_id')
    # ### end Alembic commands ###
