""" corrigir mapper de novas tabelas, empresa, users em transactions

Revision ID: b292569996ed
Revises: 0d838f473b20
Create Date: 2025-08-21 14:47:55.839387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b292569996ed'
down_revision: Union[str, Sequence[str], None] = '0d838f473b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
